name = "delete-messages-bot"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-12-27"

[build]
command = "dune build --profile=release"
upload.dir = "_build/default/src"
upload.main = "main.bc.js"
upload.format = "modules"
upload.rules = [{ type = "ESModule", globs = ["**/*.js"] }]
